/**
 * Image helpers for the Lumo 2.0 proxy.
 *
 * Inbound: OpenAI image_url / input_image / markdown data URLs -> WireImage.
 * Outbound: generated bytes -> markdown data URL (round-trips via the same parser).
 */

import { randomUUID } from 'crypto';
import type { Role, WireImage } from '@lumo/types-api.js';
import { logger } from '../app/logger.js';

export interface GeneratedImage {
  image_id: string;
  mimeType: string;
  /** Raw image bytes as standard base64 (no data: prefix). */
  data: string;
}

const MARKDOWN_IMAGE_RE = /!\[([^\]]*)\]\((data:[^)]+)\)/g;
const DATA_URL_RE = /^data:([^;,]+);base64,(.+)$/s;

export function sniffImageMime(dataBase64: string): string {
  let bytes: Buffer;
  try {
    bytes = Buffer.from(dataBase64.slice(0, 32), 'base64');
  } catch {
    return 'image/png';
  }
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return 'image/jpeg';
  if (bytes.length >= 8 && bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) return 'image/png';
  if (bytes.length >= 6 && bytes[0] === 0x47 && bytes[1] === 0x49 && bytes[2] === 0x46) return 'image/gif';
  if (bytes.length >= 12 && bytes.toString('ascii', 0, 4) === 'RIFF' && bytes.toString('ascii', 8, 12) === 'WEBP') {
    return 'image/webp';
  }
  return 'image/png';
}

export function formatImageMarkdown(image: GeneratedImage): string {
  return `![lumo:${image.image_id}](data:${image.mimeType};base64,${image.data})`;
}

export function formatImagesForClient(images: GeneratedImage[]): string {
  if (images.length === 0) return '';
  return '\n\n' + images.map(formatImageMarkdown).join('\n\n');
}

/** Replace data-URL markdown with a short label (CLI / logs). */
export function redactGeneratedImages(text: string): string {
  return text.replace(MARKDOWN_IMAGE_RE, (_full, alt: string) => `\n[image ${alt || 'generated'}]\n`);
}

export function parseDataUrl(url: string): { mimeType: string; data: string } | null {
  const match = url.trim().match(DATA_URL_RE);
  if (!match) return null;
  return { mimeType: match[1], data: match[2].replace(/\s/g, '') };
}

export function wireImageFromData(data: string, imageId?: string, mimeType?: string): WireImage {
  return {
    encrypted: false,
    image_id: imageId || randomUUID(),
    data,
  };
}

function imageIdFromAlt(alt: string): string | undefined {
  const match = alt.match(/^lumo:(.+)$/);
  return match?.[1];
}

/** Pull markdown data-URL images out of text. Returns leftover text + images. */
export function extractMarkdownImages(text: string): { text: string; images: WireImage[] } {
  const images: WireImage[] = [];
  const leftover = text.replace(MARKDOWN_IMAGE_RE, (_full, alt: string, url: string) => {
    const parsed = parseDataUrl(url);
    if (!parsed) return _full;
    images.push(wireImageFromData(parsed.data, imageIdFromAlt(alt)));
    return '';
  });
  return { text: leftover.replace(/\n{3,}/g, '\n\n').trim(), images };
}

export function concatBase64(left: string, right: string): string {
  return Buffer.concat([Buffer.from(left, 'base64'), Buffer.from(right, 'base64')]).toString('base64');
}

/**
 * Collect image payloads from OpenAI-style content (string, parts array, or object).
 * HTTP(S) URLs are fetched when `fetchUrl` is provided.
 */
export async function extractImagesFromContent(
  content: unknown,
  options: { maxBytes: number; fetchUrl?: (url: string) => Promise<string | null> } = { maxBytes: 4 * 1024 * 1024 },
): Promise<{ text: string; images: WireImage[] }> {
  if (typeof content === 'string') {
    return extractMarkdownImages(content);
  }

  const textParts: string[] = [];
  const images: WireImage[] = [];

  const consumeUrl = async (url: string, imageId?: string) => {
    const parsed = parseDataUrl(url);
    if (parsed) {
      if (Buffer.from(parsed.data, 'base64').length > options.maxBytes) {
        logger.warn({ maxBytes: options.maxBytes }, 'Dropping inbound image over maxInputBytes');
        return;
      }
      images.push(wireImageFromData(parsed.data, imageId, parsed.mimeType));
      return;
    }
    if (options.fetchUrl && /^https?:\/\//i.test(url)) {
      const data = await options.fetchUrl(url);
      if (data) images.push(wireImageFromData(data, imageId));
    }
  };

  const parts = Array.isArray(content) ? content : (content && typeof content === 'object' ? [content] : []);
  for (const part of parts) {
    if (typeof part === 'string') {
      const extracted = extractMarkdownImages(part);
      if (extracted.text) textParts.push(extracted.text);
      images.push(...extracted.images);
      continue;
    }
    if (typeof part !== 'object' || part === null) continue;
    const obj = part as Record<string, unknown>;

    if (typeof obj.text === 'string') {
      const extracted = extractMarkdownImages(obj.text);
      if (extracted.text) textParts.push(extracted.text);
      images.push(...extracted.images);
    }

    const imageUrl = obj.image_url;
    if (typeof imageUrl === 'string') {
      await consumeUrl(imageUrl, typeof obj.image_id === 'string' ? obj.image_id : undefined);
    } else if (imageUrl && typeof imageUrl === 'object') {
      const rec = imageUrl as Record<string, unknown>;
      if (typeof rec.url === 'string') {
        await consumeUrl(rec.url, typeof rec.image_id === 'string' ? rec.image_id : undefined);
      }
    }
  }

  return { text: textParts.join('\n').trim(), images };
}

export async function fetchImageAsBase64(url: string, maxBytes: number): Promise<string | null> {
  try {
    const res = await fetch(url, { signal: AbortSignal.timeout(15000) });
    if (!res.ok) {
      logger.warn({ url, status: res.status }, 'Failed to fetch inbound image URL');
      return null;
    }
    const buf = Buffer.from(await res.arrayBuffer());
    if (buf.length > maxBytes) {
      logger.warn({ url, bytes: buf.length, maxBytes }, 'Dropping fetched image over maxInputBytes');
      return null;
    }
    return buf.toString('base64');
  } catch (error) {
    logger.warn({ error, url }, 'Failed to fetch inbound image URL');
    return null;
  }
}

export function turnFromStoredContent(role: Role, content?: string): {
  role: Role;
  content?: string;
  images?: WireImage[];
} {
  const extracted = extractMarkdownImages(content ?? '');
  return {
    role,
    content: extracted.text,
    ...(extracted.images.length > 0 ? { images: extracted.images } : {}),
  };
}

export const IMAGE_TOOLS = ['generate_image', 'describe_image', 'edit_image'] as const;
